version: "3.8"
services:
  grafana:
    image: grafana/grafana:latest
    networks:
      - app-network
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:latest
    networks:
      - app-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

networks:
  app-network:
    external: true
