version: "3"

services:
  traefik:
    image: traefik:latest
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak-data:/opt/jboss/keycloak/standalone/data
  kafka:
      image: wurstmeister/kafka:latest
      environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092  # Kafka listens on all interfaces
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.0.200:9092  # Update with the correct host
      ports:
        - "9092:9092"  # Ensure Kafka listens on port 9092

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  fraud-detection-service:
    build:
      context: ./fraud-detection # Directory where your Dockerfile is located
    image: pycaret-fraud-detection:latest
    ports:
      - "8085:5000"

  notification-service:
    image: jookies/jasmin:latest
    ports:
      - "2775:2775"
      - "8990:8990"
    environment:
      - JASMIN_USER=admin
      - JASMIN_PASSWORD=admin

  reporting-service:
    image: apache/superset
    environment:
      - SUPERSET_ENV=prod
      - SECRET_KEY=p8mykGPbbLYB6p7FSuE5nyeuHtjDF24JO8ujB597GhDlsmS8cPRFihGp
    ports:
      - "8088:8088"
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py


  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  postgres-data:
    driver: local
